# Generated by Django 4.2.13 on 2024-08-08 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название района')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Описание')),
                ('property_type', models.CharField(choices=[('new', 'Новостройка'), ('old', 'Вторичный фонд')], max_length=100, verbose_name='Тип недвижимости')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('rooms_qty_from', models.PositiveSmallIntegerField(verbose_name='Кол-во комнат от')),
                ('rooms_qty_to', models.PositiveSmallIntegerField(verbose_name='Кол-во комнат до')),
                ('quadrature_from', models.PositiveSmallIntegerField(verbose_name='Квадратура от')),
                ('quadrature_to', models.PositiveSmallIntegerField(verbose_name='Квадратура до')),
                ('floor_from', models.PositiveSmallIntegerField(verbose_name='Этаж от')),
                ('floor_to', models.PositiveSmallIntegerField(verbose_name='Этаж до')),
                ('repair_type', models.CharField(max_length=100, verbose_name='Ремонт')),
                ('auction_allowed', models.BooleanField(default=False, verbose_name='Торг уместен?')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='api.district', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
