# Generated by Django 4.2.13 on 2024-08-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_advertisementgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
