# Generated by Django 4.2.13 on 2024-09-03 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_alter_advertisement_repair_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementRequestForModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('moderation', 'На модерации'), ('completed', 'Прошло модерацию')], default='moderation', max_length=30, verbose_name='Статус объявления')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.advertisement')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Риелтор')),
            ],
            options={
                'verbose_name': 'Объявление для модерации',
                'verbose_name_plural': 'Объявления для модерации',
            },
        ),
    ]
