# Generated by Django 4.2.13 on 2024-09-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_advertisementrequestformoderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='creation_year',
            field=models.IntegerField(default=0, verbose_name='Год постройки'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='is_studio',
            field=models.BooleanField(default=False, verbose_name='Студия ?'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='repair_type',
            field=models.CharField(blank=True, choices=[('with', 'С ремонтом'), ('without', 'Без ремонта'), ('designed', 'Дизайнерский ремонт'), ('rough', 'Черновая'), ('pre_finished', 'Предчистовая')], max_length=100, null=True, verbose_name='Ремонт'),
        ),
    ]
