# Generated by Django 4.2.13 on 2024-09-06 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_advertisement_address_advertisement_creation_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='Прошла модерацию?'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to=settings.AUTH_USER_MODEL, verbose_name='Риелтор'),
        ),
    ]
