# Generated by Django 4.2.13 on 2024-09-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_advertisement_is_moderated_advertisement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisementrequestformoderation',
            name='status',
        ),
        migrations.AddField(
            model_name='advertisementrequestformoderation',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='Прошла модерацию?'),
        ),
    ]
