# Generated by Django 4.2.13 on 2024-09-17 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_advertisementrequestformoderation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.category', verbose_name='Тип объекта'),
        ),
    ]
