# Generated by Django 4.2.13 on 2024-09-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_userrequest_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='object_type',
            field=models.CharField(max_length=100, verbose_name='Тип объекта'),
        ),
    ]
