# Generated by Django 4.2.13 on 2024-09-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_userrequest_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='object_type',
            field=models.CharField(blank=True, choices=[('commercial', 'Коммерческий'), ('house', 'Дом'), ('new_building', 'Новостройка'), ('flat', 'Квартира')], max_length=100, null=True, verbose_name='Тип объекта'),
        ),
    ]
