# Generated by Django 4.2.13 on 2024-09-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_userrequest_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('buy', 'Покупка'), ('rent', 'Аренда')], max_length=100, null=True, verbose_name='Тип операции'),
        ),
    ]
