# Generated by Django 4.2.13 on 2024-09-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_userrequest_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('buy', 'Покупка'), ('rent', 'Аренда')], max_length=100, null=True, verbose_name='Тип операции'),
        ),
    ]
