# Generated by Django 4.2.13 on 2024-09-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_advertisement_category_ru_advertisement_category_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='house_quadrature',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общая площадь участка'),
        ),
    ]
