# Generated by Django 4.2.13 on 2024-10-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_advertisement_house_quadrature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisementgallery',
            options={'verbose_name': 'Фото объявления', 'verbose_name_plural': 'Фото объявлений'},
        ),
    ]
