# Generated by Django 4.2.13 on 2024-10-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_advertisementmoderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementmoderation',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='Прошла модерацию ?'),
        ),
    ]
