# Generated by Django 4.2.13 on 2024-10-10 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_advertisementmoderation_is_moderated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvertisementModeration',
        ),
    ]
