# Generated by Django 4.2.13 on 2024-10-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_advertisementrequestformoderation_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='house_quadrature_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='площадь участка до'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='house_quadrature',
            field=models.IntegerField(blank=True, null=True, verbose_name='площадь участка от'),
        ),
    ]
