# Generated by Django 4.2.13 on 2024-10-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_advertisement_house_quadrature_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='house_quadrature',
            new_name='house_quadrature_from',
        ),
    ]
