# Generated by Django 4.2.13 on 2024-11-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_rename_house_quadrature_advertisement_house_quadrature_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='operation_type_ru',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='operation_type_uz',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='property_type_ru',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='property_type_uz',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='repair_type_ru',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='repair_type_uz',
        ),
    ]
