# Generated by Django 4.2.13 on 2024-08-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_realtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m', verbose_name='Фото'),
        ),
    ]
