# Generated by Django 4.2.13 on 2024-08-14 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_tg_username_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
