# Generated by Django 4.2.13 on 2024-08-14 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0007_remove_user_lastname_remove_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
