# Generated by Django 4.2.13 on 2024-08-14 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0008_rename_user_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
