# Generated by Django 4.2.13 on 2024-10-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_customuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_user_id',
            field=models.BigIntegerField(null=True, verbose_name='ID пользователя в телеграм'),
        ),
    ]
